name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04  # 显式指定新版系统
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 必须升级到 v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1   # 使用最新稳定版
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 2024-07    # 时间戳缓存版本

      - name: Setup Pages
        uses: actions/configure-pages@v4  # 升级到 v4

      - name: Build with Jekyll
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site
          retention-days: 1  # 添加清理策略

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # 升级到 v3