name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ master ]  # 替换为你的源码分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 步骤2：设置 Ruby 环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2  # 替换为你的 Ruby 版本
          bundler-cache: true
            # 显式声明目标平台
          platforms: x86_64-linux,x86_64-mingw-ucrt
      - name: Install dependencies
        run: |
          bundle config set force_ruby_platform true
          bundle install --jobs 4 --retry 3
      # 步骤3：安装系统依赖（可选）
      - name: Install System Dependencies
        run: sudo apt-get install -y build-essential

      # 步骤4：安装项目依赖
      - name: Install Bundler Gems
        run: |
          bundle config path vendor/bundle
          bundle install

      # 步骤5：构建网站
      - name: Build Site
        run: bundle exec jekyll build  # 替换为你的构建命令

      # 步骤6：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 公共仓库使用默认 Token
          # deploy_key: ${{ secrets.DEPLOY_KEY }}    # 私有仓库需配置 Deploy Key
          publish_dir: /_site  # 替换为你的部署目录
          publish_branch: deploy  # 替换为你的发布分支